import { StyleSheet } from 'react-native';
import { colors } from '@/lib/theme';

export const s = StyleSheet.create({
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: 'Inter_800ExtraBold',
    color: colors.textPrimary,
    letterSpacing: -0.4,
    marginTop: 24,
    paddingHorizontal: 4,
  },
  container: { flex: 1, backgroundColor: '#f2f2f7' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 17, fontWeight: '700', color: colors.textPrimary, flex: 1, marginHorizontal: 10 },
  content: { padding: 16, gap: 12, paddingBottom: 180 },

  // ── Uber hero header ──────────────────────────────────────────
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  heroLeft: { flex: 1, marginRight: 12 },
  heroOrderNumber: {
    fontSize: 26,
    fontFamily: 'Inter_800ExtraBold',
    fontWeight: '800',
    color: colors.textPrimary,
    lineHeight: 30,
    letterSpacing: -0.5,
  },
  heroMaterial: {
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    color: colors.textMuted,
    marginTop: 3,
  },

  // ── Horizontal status stepper ──────────────────────────────────
  stepperCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  stepperWrap: { position: 'relative', paddingBottom: 4 },
  stepperTrack: {
    position: 'absolute',
    top: 11,
    left: '10%',
    right: '10%',
    height: 2,
    backgroundColor: '#e5e7eb',
  },
  stepperFill: {
    position: 'absolute',
    top: 11,
    left: '10%',
    height: 2,
    backgroundColor: colors.primary,
  },
  stepperDotsRow: { flexDirection: 'row' },
  stepCol: { flex: 1, alignItems: 'center', gap: 6 },
  stepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotDone: { backgroundColor: colors.primary },
  stepDotActive: {
    backgroundColor: colors.primary,
    width: 26,
    height: 26,
    borderRadius: 13,
    shadowColor: '#111827',
    shadowOpacity: 0.35,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  stepDotPulse: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#fff' },
  stepLabel: {
    fontSize: 10,
    color: '#d1d5db',
    textAlign: 'center',
    fontFamily: 'Inter_400Regular',
  },
  stepLabelDone: { color: colors.textDisabled },
  stepLabelActive: {
    color: colors.textPrimary,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  stepHint: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 12,
    fontFamily: 'Inter_400Regular',
  },

  liveTrackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  liveTrackLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  liveIndicator: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  liveTrackTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
    fontFamily: 'Inter_800ExtraBold',
  },
  liveTrackSub: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
    fontFamily: 'Inter_400Regular',
  },
  driverCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  driverInfo: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  driverAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#e5e7eb' },
  driverAvatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverAvatarInitials: { fontSize: 15, fontWeight: '700', color: '#fff' },
  driverName: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  driverRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 2 },
  driverRatingText: { fontSize: 12, color: colors.textMuted, marginLeft: 3, fontWeight: '500' },
  driverPhone: { fontSize: 12, color: colors.textMuted, marginTop: 1 },
  driverPlate: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
    backgroundColor: colors.bgMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  callBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgMuted,
  },
  callBtnText: { display: 'none' },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'transparent',
  },
  itemBorder: { borderBottomWidth: 0 },
  itemName: { fontSize: 14, fontWeight: '600', color: colors.textPrimary },
  itemMeta: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  itemTotal: { fontSize: 15, fontWeight: '700', color: colors.textSecondary },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: colors.bgSubtle,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  totalLabel: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  totalValue: { fontSize: 18, fontWeight: '800', color: colors.textPrimary },
  callSiteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    margin: 12,
    padding: 10,
    backgroundColor: colors.bgMuted,
    borderRadius: 10,
  },
  callSiteBtnText: { fontSize: 13, fontWeight: '600', color: colors.textSecondary },
  actions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 8,
  },
  pendingNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgMuted,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#4b5563',
  },
  pendingText: { fontSize: 13, fontWeight: '600', color: colors.textMuted },
  deliveredNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgSubtle,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: colors.textPrimary,
  },
  deliveredText: { fontSize: 13, fontWeight: '600', color: colors.textPrimary },
  cancelledNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.dangerBg,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: colors.textPrimary,
  },
  cancelledText: { fontSize: 13, fontWeight: '600', color: colors.dangerText },
  cancelOrderBtn: {
    alignItems: 'center',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.textPrimary,
  },
  cancelOrderBtnText: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
  payNowBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 14,
    padding: 16,
  },
  payNowBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },
  stripeUnavailableBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fffbeb',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
    padding: 12,
  },
  stripeUnavailableText: { flex: 1, fontSize: 13, color: '#92400e', lineHeight: 18 },
  invoiceBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#eff6ff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    padding: 14,
  },
  invoiceBannerTitle: { fontSize: 14, fontWeight: '700', color: '#1d4ed8', marginBottom: 2 },
  invoiceBannerDesc: { fontSize: 13, color: '#1e40af', lineHeight: 18 },
  rateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 100,
    padding: 14,
    justifyContent: 'center',
  },
  rateBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  // ETA card
  etaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: colors.textPrimary,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  etaLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  etaEmoji: { fontSize: 28 },
  etaLabel: { fontSize: 11, color: colors.textMuted, fontWeight: '500' },
  etaValue: { fontSize: 20, fontWeight: '800', color: colors.textPrimary, marginTop: 2 },

  // Re-order button
  reorderBtn: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  reorderBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },

  confirmReceiptBtn: {
    backgroundColor: '#16a34a',
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  confirmReceiptBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },

  alreadyRated: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgMuted,
    borderRadius: 12,
    padding: 12,
  },
  alreadyRatedText: { fontSize: 13, fontWeight: '600', color: colors.textMuted },

  // Documents section
  docRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 0,
    borderBottomColor: colors.border,
    gap: 12,
  },
  docInfo: { flex: 1 },
  docTitle: { fontSize: 14, fontWeight: '600', color: colors.textPrimary },
  docStatus: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  docDownloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  docDownloadText: { fontSize: 12, fontWeight: '700', color: '#fff' },
  docPendingBadge: {
    backgroundColor: colors.bgMuted,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  docPendingText: { fontSize: 12, fontWeight: '600', color: colors.textDisabled },

  trackingCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  trackingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#fff7f7',
    borderBottomWidth: 1,
    borderBottomColor: '#fee2e2',
  },
  trackingTitle: { fontSize: 12, fontWeight: '700', color: colors.textSecondary, flex: 1 },

  // Order timeline
  tlRow: { flexDirection: 'row', minHeight: 44 },
  tlLeft: { alignItems: 'center', width: 28, marginRight: 12 },
  tlDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.border,
  },
  tlDotDone: { backgroundColor: colors.primary, borderColor: colors.textPrimary },
  tlDotActive: {
    backgroundColor: '#fff',
    borderColor: colors.textPrimary,
    borderWidth: 3,
  },
  tlDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  tlLine: { flex: 1, width: 2, backgroundColor: '#e5e7eb', marginVertical: 2 },
  tlLineDone: { backgroundColor: colors.primary },
  tlContent: { flex: 1, paddingTop: 2, paddingBottom: 10 },
  tlLabel: { fontSize: 14, fontWeight: '500', color: colors.textDisabled },
  tlLabelDone: { color: colors.textSecondary, fontWeight: '600' },
  tlLabelActive: { color: colors.textPrimary, fontWeight: '700' },
  tlHint: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  chatDriverBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgMuted,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatDriverBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },

  // Delivery proof section
  proofTime: { fontSize: 11, color: colors.textDisabled, marginLeft: 'auto' },
  proofPhotoRow: { paddingHorizontal: 14, paddingBottom: 14, paddingTop: 10, gap: 10 },
  proofPhoto: {
    width: 140,
    height: 140,
    borderRadius: 10,
    backgroundColor: '#e5e7eb',
  },
  proofNoPhoto: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  proofNoPhotoText: { fontSize: 13, color: colors.textMuted },

  // Weighing slip photo
  weighingSlipPhoto: {
    width: '100%',
    height: 220,
    borderRadius: 10,
    backgroundColor: colors.bgMuted,
    marginTop: 10,
  },
  weighingWeight: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
    marginLeft: 'auto',
  },

  // Amendment button
  amendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.bgSubtle,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 4,
  },
  amendBtnText: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },

  // Amendment sheet fields
  amendField: { gap: 6 },
  amendLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  amendInput: {
    backgroundColor: colors.bgSubtle,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.textPrimary,
  },
  amendWindowRow: { flexDirection: 'row', gap: 8 },
  amendWindowBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
  },
  amendWindowBtnActive: { backgroundColor: colors.primary },
  amendWindowBtnText: { fontSize: 12, fontWeight: '600', color: colors.textMuted },
  amendWindowBtnTextActive: { color: '#fff' },
  amendSubmitBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 4,
  },
  amendSubmitBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },

  // Report issue button
  reportIssueBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    marginTop: 4,
  },
  reportIssueBtnText: {
    fontSize: 14,
    color: colors.textMuted,
    fontWeight: '500',
  },

  // Dispute filed confirmation
  disputeFiledNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#fffbeb',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
    marginTop: 4,
  },
  disputeFiledText: {
    fontSize: 13,
    color: '#92400e',
    fontWeight: '500',
  },

  // Dispute bottom sheet
  disputeReasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#fff',
  },
  disputeReasonRowActive: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.bgSubtle,
  },
  disputeRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  disputeRadioActive: {
    borderColor: colors.textPrimary,
  },
  disputeRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  disputeReasonText: {
    flex: 1,
    fontSize: 14,
    color: colors.textSecondary,
  },
  disputeReasonTextActive: {
    color: colors.textPrimary,
    fontWeight: '600',
  },
  disputeDetailsInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: '#fff',
    height: 80,
    textAlignVertical: 'top',
  },
  disputeSubmitBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disputeSubmitBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },

  // ── Exception banner ──────────────────────────────────────────
  exceptionBanner: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fcd34d',
    borderRadius: 12,
    padding: 14,
  },
  exceptionBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#92400e',
  },
  exceptionBannerMeta: {
    fontSize: 13,
    color: '#b45309',
    fontWeight: '500',
  },
  exceptionBannerNote: {
    fontSize: 13,
    color: '#78350f',
    marginTop: 2,
  },
  primaryActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 10,
    padding: 14,
  },
  primaryActionBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
  secondaryActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.bgMuted,
    borderRadius: 10,
    padding: 12,
  },
  secondaryActionBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  secondaryActionBtnDanger: {
    backgroundColor: colors.dangerBg,
  },
  secondaryActionBtnDangerText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#991b1b',
  },
  chatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.bgSubtle,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
  },
  chatBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  statusMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.bgMuted,
    borderRadius: 8,
    padding: 10,
  },
  statusMessageText: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '500',
  },
  exceptionBannerFlat: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: colors.bgMuted,
    borderRadius: 8,
    padding: 12,
    borderWidth: 0,
  },
  exceptionBannerFlatTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  exceptionBannerFlatSub: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  priceRowSimple: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: 'transparent',
  },
  priceLabel: {
    fontSize: 13,
    color: colors.textMuted,
    fontWeight: '500',
  },
  priceValue: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  priceDivider: {
    height: 1,
    backgroundColor: colors.bgMuted,
    marginVertical: 4,
  },
  pendingSurchargeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#fffbeb',
    borderRadius: 10,
    marginHorizontal: 4,
    marginVertical: 3,
    gap: 8,
  },
  pendingSurchargeLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400e',
  },
  pendingSurchargeMeta: {
    fontSize: 11,
    color: '#b45309',
    marginTop: 1,
  },
  pendingSurchargeAmount: {
    fontSize: 13,
    fontWeight: '700',
    color: '#92400e',
  },
  pendingSurchargeActions: {
    flexDirection: 'row',
    gap: 6,
  },
  rejectBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fca5a5',
    backgroundColor: '#fff',
    minWidth: 72,
    alignItems: 'center',
  },
  rejectBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ef4444',
  },
  approveBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: colors.primary,
    minWidth: 88,
    alignItems: 'center',
  },
  approveBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  totalRowFinal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  totalLabelFinal: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  totalValueFinal: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
  },
});
