import { StyleSheet } from 'react-native';
import { colors } from '@/lib/theme';

export const s = StyleSheet.create({
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: 'Inter_800ExtraBold',
    color: colors.textPrimary,
    letterSpacing: -0.4,
    marginTop: 24,
    paddingHorizontal: 4,
  },
  container: { flex: 1, backgroundColor: '#f2f2f7' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textPrimary,
    flex: 1,
    marginHorizontal: 10,
  },
  content: { padding: 16, gap: 12, paddingBottom: 180 },

  // ── Uber hero header ──────────────────────────────────────────
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 28,
    backgroundColor: '#fff',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    marginBottom: 16,
  },
  heroLeft: { flex: 1 },
  heroMaterialHeading: {
    fontSize: 26,
    fontFamily: 'Inter_800ExtraBold',
    fontWeight: '800',
    color: '#111827',
    lineHeight: 30,
    letterSpacing: -0.6,
  },
  heroOrderNumberSub: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    color: '#6b7280',
    marginTop: 4,
  },

  // ── Horizontal status stepper ──────────────────────────────────
  stepperCard: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 24,
    marginBottom: 12,
  },
  stepperWrap: { position: 'relative', paddingBottom: 4 },
  stepperTrack: {
    position: 'absolute',
    top: 12,
    left: '10%',
    right: '10%',
    height: 2,
    backgroundColor: '#f3f4f6',
  },
  stepperFill: {
    position: 'absolute',
    top: 11,
    left: '10%',
    height: 2,
    backgroundColor: '#10b981',
  },
  stepperDotsRow: { flexDirection: 'row' },
  stepCol: { flex: 1, alignItems: 'center', gap: 6 },
  stepDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#e5e7eb',
  },
  stepDotDone: { backgroundColor: '#10b981', borderColor: '#10b981' },
  stepDotActive: {
    backgroundColor: '#111827',
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 6,
    borderColor: '#e5e7eb',
  },
  stepDotPulse: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#fff' },
  stepLabel: {
    fontSize: 11,
    color: '#9ca3af',
    textAlign: 'center',
    fontFamily: 'Inter_500Medium',
  },
  stepLabelDone: { color: '#6b7280' },
  stepLabelActive: {
    color: '#111827',
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  stepTs: {
    fontSize: 9,
    color: '#9ca3af',
    textAlign: 'center' as const,
    fontFamily: 'Inter_500Medium',
    marginTop: -2,
  },
  stepHint: {
    fontSize: 13,
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 16,
    fontFamily: 'Inter_500Medium',
  },

  // ── Inline live tracking map card ─────────────────────────────
  inlineTrackCard: {
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 12,
  },
  mapEtaOverlay: {
    position: 'absolute',
    top: 14,
    left: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#111827',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  mapEtaDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#10b981',
  },
  mapEtaText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  pinDelivery: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2.5,
    borderColor: '#fff',
  },
  pinDriver: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },

  liveTrackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    padding: 20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginBottom: 1,
  },
  liveTrackLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  liveIndicator: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#10b981',
  },
  liveTrackTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#111827',
    fontFamily: 'Inter_800ExtraBold',
  },
  liveTrackSub: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 4,
    fontFamily: 'Inter_500Medium',
  },
  driverCard: {
    backgroundColor: '#fff',
    padding: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    marginBottom: 12,
  },
  driverInfo: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  driverAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#f3f4f6' },
  driverAvatarFallback: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverAvatarInitials: { fontSize: 16, fontWeight: '700', color: '#fff' },
  driverName: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: 'Inter_800ExtraBold',
    color: '#111827',
  },
  driverRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 2 },
  driverRatingText: { fontSize: 13, color: '#6b7280', marginLeft: 3, fontWeight: '500' },
  driverPhone: { fontSize: 13, color: '#6b7280', marginTop: 2 },
  driverPlate: {
    fontSize: 13,
    fontWeight: '700',
    color: '#374151',
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  callBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
  },
  callBtnText: { display: 'none' },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  itemBorder: { borderBottomWidth: 0 },
  itemName: { fontSize: 15, fontWeight: '700', color: '#111827' },
  itemMeta: { fontSize: 13, color: '#6b7280', marginTop: 4 },
  itemTotal: { fontSize: 15, fontWeight: '700', color: '#111827' },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 4,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    marginTop: 8,
  },
  totalLabel: { fontSize: 15, fontWeight: '700', color: '#374151' },
  totalValue: {
    fontSize: 20,
    fontWeight: '800',
    fontFamily: 'Inter_800ExtraBold',
    color: '#111827',
  },
  callSiteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    margin: 12,
    padding: 10,
    backgroundColor: colors.bgMuted,
    borderRadius: 10,
  },
  callSiteBtnText: { fontSize: 13, fontWeight: '600', color: colors.textSecondary },
  actions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40, // Increased safe area bottom padding
    gap: 12,
  },
  pendingNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgMuted,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#4b5563',
  },
  pendingText: { fontSize: 13, fontWeight: '600', color: colors.textMuted },
  deliveredNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgSubtle,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: colors.textPrimary,
  },
  deliveredText: { fontSize: 13, fontWeight: '600', color: colors.textPrimary },
  cancelledNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.dangerBg,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: colors.textPrimary,
  },
  cancelledText: { fontSize: 13, fontWeight: '600', color: colors.dangerText },
  cancelOrderBtn: {
    alignItems: 'center',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.textPrimary,
  },
  cancelOrderBtnText: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
  primaryActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingVertical: 18,
  },
  primaryActionBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },
  secondaryActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#f3f4f6',
    borderRadius: 999,
    paddingVertical: 18,
  },
  secondaryActionBtnText: { fontSize: 16, fontWeight: '600', color: '#111827' },
  secondaryActionBtnDanger: { backgroundColor: '#fef2f2' },
  secondaryActionBtnDangerText: { fontSize: 16, fontWeight: '600', color: '#ef4444' },
  stripeUnavailableBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fffbeb',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
    padding: 12,
  },
  stripeUnavailableText: { flex: 1, fontSize: 13, color: '#92400e', lineHeight: 18 },
  invoiceBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#eff6ff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    padding: 14,
  },
  invoiceBannerTitle: { fontSize: 14, fontWeight: '700', color: '#1d4ed8', marginBottom: 2 },
  invoiceBannerDesc: { fontSize: 13, color: '#1e40af', lineHeight: 18 },
  rateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 100,
    padding: 14,
    justifyContent: 'center',
  },
  rateBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  // ETA card
  etaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: colors.textPrimary,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  etaLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  etaEmoji: { fontSize: 28 },
  etaLabel: { fontSize: 11, color: colors.textMuted, fontWeight: '500' },
  etaValue: { fontSize: 20, fontWeight: '800', color: colors.textPrimary, marginTop: 2 },

  // Re-order button
  reorderBtn: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingVertical: 18,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  reorderBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },

  confirmReceiptBtn: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingVertical: 18,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  confirmReceiptBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },

  alreadyRated: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgMuted,
    borderRadius: 12,
    padding: 12,
  },
  alreadyRatedText: { fontSize: 13, fontWeight: '600', color: colors.textMuted },

  // Documents section
  docRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingVertical: 12,
    borderBottomWidth: 0,
    borderBottomColor: '#f3f4f6',
    gap: 12,
  },
  docInfo: { flex: 1 },
  docTitle: { fontSize: 15, fontWeight: '700', color: '#111827' },
  docStatus: { fontSize: 13, color: '#6b7280', marginTop: 2 },
  docDownloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#111827',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  docDownloadText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  docPendingBadge: {
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  docPendingText: { fontSize: 13, fontWeight: '600', color: '#9ca3af' },

  trackingCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    overflow: 'hidden',
  },
  trackingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: '#fff7f7',
    borderBottomWidth: 1,
    borderBottomColor: '#fee2e2',
  },
  trackingTitle: { fontSize: 14, fontWeight: '700', color: '#ef4444', flex: 1 },

  // Order timeline
  tlRow: { flexDirection: 'row', minHeight: 48 },
  tlLeft: { alignItems: 'center', width: 32, marginRight: 16 },
  tlDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#e5e7eb',
  },
  tlDotDone: { backgroundColor: '#10b981', borderColor: '#10b981' },
  tlDotActive: {
    backgroundColor: '#fff',
    borderColor: '#111827',
    borderWidth: 3,
  },
  tlDotInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#111827',
  },
  tlLine: { flex: 1, width: 2, backgroundColor: '#f3f4f6', marginVertical: 4 },
  tlLineDone: { backgroundColor: '#10b981' },
  tlContent: { flex: 1, paddingTop: 0, paddingBottom: 16 },
  tlLabel: { fontSize: 16, fontWeight: '600', color: '#9ca3af' },
  tlLabelDone: { color: '#374151', fontWeight: '700' },
  tlLabelActive: { color: '#111827', fontWeight: '800' },
  tlHint: { fontSize: 14, color: '#6b7280', marginTop: 4 },
  chatDriverBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f3f4f6',
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  chatDriverBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },

  // Delivery proof section
  proofTime: { fontSize: 12, color: '#9ca3af', marginLeft: 'auto', fontWeight: '500' },
  proofPhotoRow: { paddingHorizontal: 0, paddingBottom: 16, paddingTop: 12, gap: 12 },
  proofPhoto: {
    width: 160,
    height: 160,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
  },
  proofNoPhoto: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 0,
    paddingVertical: 12,
  },
  proofNoPhotoText: { fontSize: 14, color: '#6b7280' },

  // Weighing slip photo
  weighingSlipPhoto: {
    width: '100%',
    height: 240,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
    marginTop: 12,
  },
  weighingWeight: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginLeft: 'auto',
  },

  // Amendment button
  amendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginTop: 8,
  },
  amendBtnText: { fontSize: 15, fontWeight: '700', color: '#111827' },

  // Amendment sheet fields
  amendField: { gap: 8 },
  amendLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#374151',
  },
  amendInput: {
    backgroundColor: '#f3f4f6',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 16,
    color: '#111827',
  },
  amendWindowRow: { flexDirection: 'row', gap: 10 },
  amendWindowBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 999,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  amendWindowBtnActive: { backgroundColor: '#111827' },
  amendWindowBtnText: { fontSize: 15, fontWeight: '700', color: '#4b5563' },
  amendWindowBtnTextActive: { color: '#fff' },
  amendSubmitBtn: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 12,
  },
  amendSubmitBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },

  // Report issue button
  reportIssueBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    marginTop: 8,
  },
  reportIssueBtnText: {
    fontSize: 15,
    color: '#6b7280',
    fontWeight: '600',
  },

  // Dispute filed confirmation
  disputeFiledNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#fffbeb',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
    marginTop: 4,
  },
  disputeFiledText: {
    fontSize: 13,
    color: '#92400e',
    fontWeight: '500',
  },

  // Dispute bottom sheet
  disputeReasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  disputeReasonRowActive: {
    borderColor: '#111827',
    backgroundColor: '#f3f4f6',
  },
  disputeRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  disputeRadioActive: {
    borderColor: '#111827',
  },
  disputeRadioDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#111827',
  },
  disputeReasonText: {
    flex: 1,
    fontSize: 15,
    color: '#4b5563',
  },
  disputeReasonTextActive: {
    color: '#111827',
    fontWeight: '700',
  },
  disputeDetailsInput: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 16,
    color: '#111827',
    backgroundColor: '#f9fafb',
    height: 100,
    textAlignVertical: 'top',
  },
  disputeSubmitBtn: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  disputeSubmitBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },

  // ── Exception banner ──────────────────────────────────────────
  exceptionBanner: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fcd34d',
    borderRadius: 12,
    padding: 14,
  },
  exceptionBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#92400e',
  },
  exceptionBannerMeta: {
    fontSize: 13,
    color: '#b45309',
    fontWeight: '500',
  },
  exceptionBannerNote: {
    fontSize: 13,
    color: '#78350f',
    marginTop: 2,
  },
  chatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#f3f4f6',
    borderRadius: 999,
    padding: 14,
  },
  chatBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  statusMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.bgMuted,
    borderRadius: 8,
    padding: 10,
  },
  statusMessageText: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '500',
  },
  exceptionBannerFlat: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    backgroundColor: '#fffaeb',
    borderRadius: 14,
    padding: 14,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  exceptionBannerFlatTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  exceptionBannerFlatSub: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  priceRowSimple: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    backgroundColor: 'transparent',
  },
  priceLabel: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '500',
  },
  priceValue: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '600',
  },
  priceDivider: {
    height: 1,
    backgroundColor: '#f3f4f6',
    marginVertical: 8,
  },
  pendingSurchargeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#fffbeb',
    borderRadius: 16,
    marginVertical: 4,
    gap: 12,
  },
  pendingSurchargeLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#92400e',
  },
  pendingSurchargeMeta: {
    fontSize: 12,
    color: '#b45309',
    marginTop: 2,
  },
  pendingSurchargeAmount: {
    fontSize: 14,
    fontWeight: '800',
    color: '#92400e',
  },
  pendingSurchargeActions: {
    flexDirection: 'row',
    gap: 8,
  },
  rejectBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fca5a5',
    backgroundColor: '#fff',
    minWidth: 72,
    alignItems: 'center',
  },
  rejectBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ef4444',
  },
  approveBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#10b981', // green for approve
    minWidth: 88,
    alignItems: 'center',
  },
  approveBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  totalRowFinal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  totalLabelFinal: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  totalValueFinal: {
    fontSize: 20,
    fontWeight: '800',
    fontFamily: 'Inter_800ExtraBold',
    color: '#111827',
  },

  floatingHeader: {
    position: 'absolute',
    top: 60,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 20,
  },
  floatingBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  floatingTitlePill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    height: 44,
    borderRadius: 22,
    paddingHorizontal: 16,
    gap: 8,
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  floatingOrderNumber: {
    fontSize: 16,
    fontWeight: '700',
  },
  floatingEta: {
    position: 'absolute',
    top: 120, // below header
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111827',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 8,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 20,
  },
  floatingBottomWrapper: {
    position: 'absolute',
    bottom: 24, // hover above the home indicator
    left: 16,
    right: 16,
    backgroundColor: '#fff',
    borderRadius: 32,
    maxHeight: '55%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
    zIndex: 30,
    overflow: 'hidden',
  },
  // ── Screenshot Clone Styles ─────────────────────────────
  minimalDriverCard: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
  },
  jobStatusLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  jobStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10b981',
  },
  jobStatusLabelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    fontFamily: 'Inter_600SemiBold',
  },
  platePill: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#E5E7EB',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  platePillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#111827',
    letterSpacing: 0.8,
    fontFamily: 'Inter_700Bold',
  },
  waitingItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  waitingItemText: {
    fontSize: 15,
    color: '#374151',
    fontWeight: '500',
  },
  minimalDriverTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  driverScreenshotAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#f3f4f6',
  },
  driverScreenshotFallback: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverScreenshotInitial: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
  },
  driverScreenshotName: {
    fontSize: 20,
    color: '#111827',
    marginBottom: 2,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  driverScreenshotRole: {
    fontSize: 14,
    color: '#6366f1', // Indigo-ish for the role
    fontWeight: '500',
  },
  screenshotActions: {
    flexDirection: 'row',
    gap: 12,
  },
  screenshotChatBtn: {
    width: 48,
    height: 48,
    backgroundColor: '#f3f4f6',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenshotCallBtn: {
    width: 64,
    height: 48,
    backgroundColor: '#f59e0b', // orange
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  
  // Progress Bar
  screenshotProgressWrap: {
    marginTop: 32,
    paddingHorizontal: 4,
  },
  screenshotBarTrack: {
    height: 4,
    backgroundColor: '#e5e7eb',
    borderRadius: 2,
    width: '100%',
    position: 'relative',
    justifyContent: 'center',
  },
  screenshotBarFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '60%', // static or dynamic depending on status
    backgroundColor: '#f59e0b',
    borderRadius: 2,
  },
  screenshotIconDotWrapper: {
    position: 'absolute',
    top: '50%',
    marginTop: -16,
    marginLeft: -16,
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#f59e0b',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  screenshotTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  screenshotTimeText: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '500',
  },
  reportIssueBtnPrimary: {
    backgroundColor: '#111827',
    borderRadius: 20,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
  },
  reportIssueBtnPrimaryText: {
    fontSize: 18,
    color: '#fff',
    fontWeight: '600',
  },
});
