import { StyleSheet } from 'react-native';
import { colors } from '@/lib/theme';


export const s = StyleSheet.create({
  // ── Specs step ──
  catBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F4F5F7',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  catBadgeMin: {
    backgroundColor: '#F4F5F7',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  catBadgeTextMin: { fontSize: 12, fontFamily: 'Inter_600SemiBold', color: colors.textMuted },

  // ── Dropdown button ──
  dropdownBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.bgCard,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
    gap: 6,
  },
  dropdownBtnText: {
    flex: 1,
    fontSize: 15,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
  },

  // ── Truck cards ──
  truckCard: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 6,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'transparent',
    gap: 4,
    position: 'relative',
  },
  truckCardActive: {
    backgroundColor: colors.bgCard,
    borderColor: colors.textPrimary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  truckCheckBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  truckLabel: {
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textMuted,
  },
  truckLabelActive: {
    color: colors.textPrimary,
  },
  truckSub: {
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
    color: colors.textDisabled,
  },

  // ── BottomSheet picker rows ──
  sheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F5F7',
  },
  sheetItemText: {
    fontSize: 15,
    fontFamily: 'Inter_500Medium',
    color: colors.textSecondary,
  },
  sheetItemTextActive: {
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
  },

  // ── Line style inputs ──
  lineFieldWrap: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 8,
  },
  lineFieldLabel: {
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
    color: colors.textDisabled,
    marginBottom: 4,
  },
  lineFieldBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  lineFieldValue: {
    flex: 1,
    fontSize: 18,
    fontFamily: 'Inter_500Medium',
    color: colors.textSecondary,
    letterSpacing: -0.2,
  },

  // ── Plain section title ──
  sectionTitleCenter: {
    textAlign: 'center',
    fontSize: 15,
    fontFamily: 'Inter_500Medium',
    color: '#4B5563',
    marginBottom: 6,
  },

  // ── Truck flat cards ──
  truckCardPlain: {
    alignItems: 'center',
    gap: 8,
  },
  truckImageWrap: {
    position: 'relative',
  },
  truckCheckCircle: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#10b981', // green like attachment
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  truckLabelPlain: {
    fontSize: 15,
    fontFamily: 'Inter_500Medium',
    color: '#4B5563',
  },
  truckSubPlain: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    color: colors.textDisabled,
  },

  // ── Line Stepper ──
  stepperLineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    paddingVertical: 12,
  },
  stepBtnDark: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#312e81', // dark purple like attachment
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperValueBox: {
    minWidth: 100,
    height: 60,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperValueLine: {
    fontSize: 32,
    fontFamily: 'Inter_500Medium',
    color: colors.textPrimary,
  },

  field: { gap: 10 },
  fieldLabel: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textDisabled, // lighter label since the form is focused
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  textInput: {
    backgroundColor: colors.bgCard,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 18, // taller tap target
    fontSize: 16,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: 16,
  },

  // ── Quantity stepper ──
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 32,
    paddingVertical: 12,
  },
  stepBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.bgCard,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  stepperValueWrap: { minWidth: 100, alignItems: 'center' },
  stepperValue: {
    fontSize: 72, // Mega large quantity size
    fontFamily: 'Inter_700Bold',
    color: colors.textPrimary,
    letterSpacing: -2.5,
    includeFontPadding: false,
  },

  // ── Unit Toggle ──
  unitToggleRow: {
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: '#F4F5F7',
    borderRadius: 16,
    padding: 6,
    marginTop: 16,
  },
  unitToggleBtn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  unitToggleBtnActive: {
    backgroundColor: colors.bgCard,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  unitToggleText: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textDisabled,
  },
  unitToggleTextActive: {
    color: colors.textPrimary,
  },

  // ── When step ──
  stepSub: { fontSize: 15, color: colors.textMuted, fontFamily: 'Inter_500Medium', lineHeight: 22 },
  asapCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#F4F5F7',
    borderWidth: 1,
    borderColor: 'transparent',
    gap: 12,
  },
  asapCardActive: {
    backgroundColor: colors.bgCard,
    borderColor: colors.textPrimary,
    borderWidth: 2,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  asapIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.bgCard,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  asapIconActive: { backgroundColor: '#F4F5F7', shadowOpacity: 0, elevation: 0 },
  asapTitle: { fontSize: 16, fontFamily: 'Inter_600SemiBold', color: colors.textPrimary },
  asapTitleActive: { color: colors.textPrimary },
  asapSub: { fontSize: 13, color: colors.textMuted, marginTop: 2, fontFamily: 'Inter_500Medium' },
  hint: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#F4F5F7',
    borderRadius: 12,
    marginTop: 8,
  },
  hintText: { fontSize: 13, color: '#4b5563', lineHeight: 18, fontFamily: 'Inter_500Medium' },
  etaHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f0fdf4',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  etaHintText: { fontSize: 13, fontFamily: 'Inter_500Medium' },

  // ── Calculator ──
  calcWrap: {
    marginTop: 20,
    borderRadius: 16,
    backgroundColor: '#F4F5F7',
    overflow: 'hidden',
  },
  calcHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  calcHeaderText: {
    flex: 1,
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textMuted,
  },
  calcBody: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    gap: 12,
  },
  calcHint: {
    fontSize: 12,
    color: colors.textDisabled,
    fontFamily: 'Inter_400Regular',
    lineHeight: 16,
  },
  calcRow: {
    flexDirection: 'row',
    gap: 8,
  },
  calcField: { flex: 1, gap: 4 },
  calcFieldLabel: {
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  calcInput: {
    backgroundColor: colors.bgCard,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  calcResult: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  calcResultLabel: {
    fontSize: 11,
    color: colors.textDisabled,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  calcResultValue: {
    fontSize: 20,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
    marginTop: 2,
  },
  calcResultSub: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    color: colors.textMuted,
  },
  calcApplyBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  calcApplyText: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    color: colors.white,
  },

  // ── Offers step ──
  offersTitle: {
    fontSize: 22,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
    letterSpacing: -0.5,
  },
  offersSub: {
    fontSize: 15,
    color: colors.textMuted,
    fontFamily: 'Inter_500Medium',
    marginTop: -8,
  },
  sortPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#fff',
  },
  sortPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.textPrimary,
  },
  sortPillText: {
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
    color: colors.textMuted,
  },
  sortPillTextActive: {
    color: '#fff',
    fontFamily: 'Inter_600SemiBold',
  },
  rfqBox: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgCard,
    padding: 16,
    gap: 12,
  },
  rfqIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F4F5F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rfqTitle: { fontSize: 16, fontFamily: 'Inter_600SemiBold', color: colors.textPrimary },
  rfqSub: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
    marginTop: 4,
    fontFamily: 'Inter_500Medium',
  },
  rfqBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 100,
    backgroundColor: '#F4F5F7',
  },
  rfqBtnText: { fontSize: 15, fontFamily: 'Inter_600SemiBold', color: colors.textPrimary },

  // ── Success state ──
  successWrap: { alignItems: 'center', paddingVertical: 32, gap: 12 },
  successIconBg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  successTitle: {
    fontSize: 26,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
    letterSpacing: -0.5,
  },
  successNum: { fontSize: 16, fontFamily: 'Inter_600SemiBold', color: colors.textMuted },
  successSub: {
    fontSize: 15,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    marginTop: 8,
    paddingHorizontal: 16,
    fontFamily: 'Inter_500Medium',
  },
  summaryCard: {
    borderRadius: 16,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: '#F9FAFB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    overflow: 'hidden',
    marginTop: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    padding: 16,
  },
  summaryText: { flex: 1, fontSize: 15, color: colors.textPrimary, fontFamily: 'Inter_500Medium' },
  summaryDivider: {
    height: 1,
    backgroundColor: '#F4F5F7',
    marginHorizontal: 16,
  },
  nextBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  nextBtnTxt: {
    fontSize: 15,
    fontFamily: 'Inter_600SemiBold',
    color: colors.white,
  },
});

// ── Offer card styles ──────────────────────────────────────────────────────────

export const oc = StyleSheet.create({
  card: {
    borderRadius: 16,
    backgroundColor: colors.bgCard,
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: 8,
    overflow: 'hidden',
  },
  cardBest: { borderColor: colors.textPrimary },
  top: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 16,
    gap: 12,
  },
  supplierName: { fontSize: 16, fontFamily: 'Inter_600SemiBold', color: colors.textPrimary },
  supplierCity: { fontSize: 14, color: colors.textMuted, marginTop: 2, fontFamily: 'Inter_500Medium' },
  bestBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
  },
  bestText: {
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    color: colors.white,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  price: {
    fontSize: 22,
    fontFamily: 'Inter_600SemiBold',
    color: colors.textPrimary,
    letterSpacing: -0.5,
  },
  priceUnit: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
    fontFamily: 'Inter_500Medium',
    textAlign: 'right',
  },
  meta: {
    flexDirection: 'row',
    gap: 16,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  metaText: { fontSize: 14, color: colors.textMuted, fontFamily: 'Inter_500Medium' },
  btn: {
    margin: 12,
    marginTop: 0,
    backgroundColor: '#F4F5F7',
    borderRadius: 100,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: { fontSize: 15, fontFamily: 'Inter_600SemiBold', color: colors.textPrimary },
  productImage: {
    width: 80,
    height: 64,
    borderRadius: 8,
    backgroundColor: colors.bgMuted,
  },
  stockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 6,
    marginBottom: 2,
  },
  stockText: {
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
  },
});
