name: 🐛 Bug Report
description: Report a bug in the project
labels: ['bug', 'needs-triage']
body:
  - type: dropdown
    id: app
    attributes:
      label: Affected App
      options:
        - Backend (NestJS)
        - Web (Next.js)
        - Mobile (Expo)
        - Multiple
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: Screenshots, logs, environment info, etc.
