import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { DocumentType, DocumentStatus, Prisma } from '@prisma/client';
import { QueryDocumentsDto } from './dto/query-documents.dto';
import { CreateDocumentDto } from './dto/create-document.dto';

@Injectable()
export class DocumentsService {
  constructor(private readonly prisma: PrismaService) {}

  /** List all documents visible to the requesting user */
  async findAll(userId: string, query: QueryDocumentsDto) {
    const where: Prisma.DocumentWhereInput = {
      ownerId: userId,
    };

    if (query.type) where.type = query.type;
    if (query.status) where.status = query.status;
    if (query.orderId) where.orderId = query.orderId;

    if (query.search) {
      where.OR = [
        { title: { contains: query.search, mode: 'insensitive' } },
        { issuedBy: { contains: query.search, mode: 'insensitive' } },
        { notes: { contains: query.search, mode: 'insensitive' } },
      ];
    }

    const [documents, total] = await Promise.all([
      this.prisma.document.findMany({
        where,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.document.count({ where }),
    ]);

    return { documents, total };
  }

  /** Get a single document by id (only if owned by user) */
  async findOne(id: string, userId: string) {
    const doc = await this.prisma.document.findFirst({
      where: { id, ownerId: userId },
    });
    if (!doc) throw new NotFoundException('Document not found');
    return doc;
  }

  /** Create a document (e.g. uploaded by user or generated by system) */
  async create(userId: string, dto: CreateDocumentDto) {
    return this.prisma.document.create({
      data: {
        ...dto,
        ownerId: userId,
        status: dto.status ?? DocumentStatus.ISSUED,
      },
    });
  }

  /** Summary counts per type for the authenticated user */
  async summary(userId: string) {
    const grouped = await this.prisma.document.groupBy({
      by: ['type'],
      where: { ownerId: userId },
      _count: { type: true },
    });

    const total = grouped.reduce((sum, g) => sum + g._count.type, 0);
    const byType = Object.fromEntries(
      grouped.map((g) => [g.type, g._count.type]),
    ) as Record<DocumentType, number>;

    return { total, byType };
  }

  /**
   * Auto-generate invoice document records when an Invoice is created.
   * Called internally by OrdersService or InvoicesService.
   */
  async generateFromInvoice(
    invoiceId: string,
    invoiceNumber: string,
    ownerId: string,
    orderId: string,
    pdfUrl?: string,
  ) {
    return this.prisma.document.create({
      data: {
        title: `Invoice ${invoiceNumber}`,
        type: DocumentType.INVOICE,
        status: DocumentStatus.ISSUED,
        fileUrl: pdfUrl,
        mimeType: 'application/pdf',
        invoiceId,
        orderId,
        ownerId,
        isGenerated: true,
      },
    });
  }

  /**
   * Auto-generate weighing slip document when material weight is confirmed.
   */
  async generateWeighingSlip(
    orderId: string,
    ownerId: string,
    weight: number,
    unit: string,
    pdfUrl?: string,
  ) {
    return this.prisma.document.create({
      data: {
        title: `Weighing Slip — ${weight} ${unit}`,
        type: DocumentType.WEIGHING_SLIP,
        status: DocumentStatus.ISSUED,
        fileUrl: pdfUrl,
        mimeType: 'application/pdf',
        orderId,
        ownerId,
        isGenerated: true,
        notes: `Confirmed weight: ${weight} ${unit}`,
      },
    });
  }

  /**
   * Auto-generate a delivery note (CMR) when a transport job is delivered.
   * Called internally by TransportJobsService.
   */
  async generateDeliveryNote(
    params: {
      orderId?: string;
      transportJobId?: string;
      ownerId: string;
      jobNumber: string;
      pickupCity: string;
      deliveryCity: string;
      driverName?: string;
    },
    pdfUrl?: string,
  ) {
    return this.prisma.document.create({
      data: {
        title: `Delivery Note — ${params.jobNumber}`,
        type: DocumentType.DELIVERY_NOTE,
        status: DocumentStatus.ISSUED,
        fileUrl: pdfUrl,
        mimeType: 'application/pdf',
        orderId: params.orderId,
        transportJobId: params.transportJobId,
        ownerId: params.ownerId,
        isGenerated: true,
        notes: `${params.pickupCity} → ${params.deliveryCity}${
          params.driverName ? ` · Driver: ${params.driverName}` : ''
        }`,
      },
    });
  }
}
