/**
 * Documents service.
 * Compliance documents (licenses, certificates, waste consignment notes).
 * Handles Supabase Storage uploads, status tracking (pending/approved/rejected),
 * signed download URLs, and expiry-date monitoring.
 */
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { SupabaseService } from '../supabase/supabase.service';
import {
  DocumentEntityType,
  DocumentLinkRole,
  DocumentType,
  DocumentStatus,
  Prisma,
} from '@prisma/client';
import { QueryDocumentsDto } from './dto/query-documents.dto';
import { CreateDocumentDto } from './dto/create-document.dto';
import PDFDocument from 'pdfkit';

@Injectable()
export class DocumentsService {
  private readonly logger = new Logger(DocumentsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly supabase: SupabaseService,
  ) {}

  /**
   * Replace a stored public Supabase Storage URL with a short-lived signed URL.
   * Falls back to the original URL if the path cannot be extracted (e.g. for
   * external or user-provided URLs that are not in Supabase Storage).
   */
  private async signDocumentFileUrl(
    fileUrl: string | null | undefined,
  ): Promise<string | null | undefined> {
    if (!fileUrl) return fileUrl;
    const path = SupabaseService.extractStoragePath(fileUrl, 'documents');
    if (!path) return fileUrl; // not a Supabase Storage URL — return as-is
    try {
      return await this.supabase.createSignedUrl('documents', path);
    } catch {
      // If signing fails (e.g. bucket not yet private), fall back to stored URL.
      this.logger.warn(`Could not sign document URL for path: ${path}`);
      return fileUrl;
    }
  }

  /** List all documents visible to the requesting user */
  async findAll(userId: string, query: QueryDocumentsDto) {
    const where: Prisma.DocumentWhereInput = {
      ownerId: userId,
    };

    if (query.type) where.type = query.type;
    if (query.status) where.status = query.status;
    if (query.orderId) where.orderId = query.orderId;
    if (query.entityType && query.entityId) {
      where.links = {
        some: {
          entityType: query.entityType,
          entityId: query.entityId,
        },
      };
    }

    if (query.search) {
      where.OR = [
        { title: { contains: query.search, mode: 'insensitive' } },
        { issuedBy: { contains: query.search, mode: 'insensitive' } },
        { notes: { contains: query.search, mode: 'insensitive' } },
      ];
    }

    const [rawDocuments, total] = await Promise.all([
      this.prisma.document.findMany({
        where,
        include: { links: true },
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.document.count({ where }),
    ]);

    const documents = await Promise.all(
      rawDocuments.map(async (doc) => ({
        ...doc,
        fileUrl: await this.signDocumentFileUrl(doc.fileUrl),
      })),
    );

    return { documents, total };
  }

  /** Get a single document by id (only if owned by user) */
  async findOne(id: string, userId: string) {
    const doc = await this.prisma.document.findFirst({
      where: { id, ownerId: userId },
      include: { links: true },
    });
    if (!doc) throw new NotFoundException('Document not found');
    return { ...doc, fileUrl: await this.signDocumentFileUrl(doc.fileUrl) };
  }

  /** Create a document (e.g. uploaded by user or generated by system) */
  async create(userId: string, dto: CreateDocumentDto) {
    const { links, ...documentData } = dto;

    const directLinks: Array<{
      entityType: DocumentEntityType;
      entityId: string;
      role: DocumentLinkRole;
    }> = [];

    if (dto.orderId)
      directLinks.push({
        entityType: DocumentEntityType.ORDER,
        entityId: dto.orderId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.invoiceId)
      directLinks.push({
        entityType: DocumentEntityType.INVOICE,
        entityId: dto.invoiceId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.transportJobId)
      directLinks.push({
        entityType: DocumentEntityType.TRANSPORT_JOB,
        entityId: dto.transportJobId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.wasteRecordId)
      directLinks.push({
        entityType: DocumentEntityType.WASTE_RECORD,
        entityId: dto.wasteRecordId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.skipHireId)
      directLinks.push({
        entityType: DocumentEntityType.SKIP_HIRE_ORDER,
        entityId: dto.skipHireId,
        role: DocumentLinkRole.PRIMARY,
      });

    return this.prisma.document.create({
      data: {
        ...documentData,
        ownerId: userId,
        status: dto.status ?? DocumentStatus.ISSUED,
        links:
          links?.length || directLinks.length
            ? {
                create: [
                  ...directLinks,
                  ...(links?.map((l) => ({
                    entityType: l.entityType,
                    entityId: l.entityId,
                    role: l.role ?? DocumentLinkRole.RELATED,
                  })) ?? []),
                ],
              }
            : undefined,
      },
      include: { links: true },
    });
  }

  /** List documents by entity context (order, invoice, framework contract, etc.). */
  async findByContext(
    userId: string,
    entityType: DocumentEntityType,
    entityId: string,
  ) {
    return this.prisma.document.findMany({
      where: {
        ownerId: userId,
        links: {
          some: { entityType, entityId },
        },
      },
      include: { links: true },
      orderBy: { createdAt: 'desc' },
    });
  }

  /** Attach an existing document to an additional business entity. */
  async addLink(
    userId: string,
    documentId: string,
    entityType: DocumentEntityType,
    entityId: string,
    role: DocumentLinkRole = DocumentLinkRole.RELATED,
  ) {
    const doc = await this.prisma.document.findFirst({
      where: { id: documentId, ownerId: userId },
      select: { id: true },
    });
    if (!doc) throw new NotFoundException('Document not found');

    await this.prisma.documentLink.upsert({
      where: {
        documentId_entityType_entityId_role: {
          documentId,
          entityType,
          entityId,
          role,
        },
      },
      update: {},
      create: {
        documentId,
        entityType,
        entityId,
        role,
      },
    });

    return this.findOne(documentId, userId);
  }

  /** Remove one context link from a document. */
  async removeLink(userId: string, documentId: string, linkId: string) {
    const doc = await this.prisma.document.findFirst({
      where: { id: documentId, ownerId: userId },
      select: { id: true },
    });
    if (!doc) throw new NotFoundException('Document not found');

    const link = await this.prisma.documentLink.findFirst({
      where: { id: linkId, documentId },
      select: { id: true },
    });
    if (!link) throw new NotFoundException('Document link not found');

    await this.prisma.documentLink.delete({ where: { id: linkId } });
    return { success: true, id: linkId };
  }

  /** Summary counts per type for the authenticated user */
  async summary(userId: string) {
    const grouped = await this.prisma.document.groupBy({
      by: ['type'],
      where: { ownerId: userId },
      _count: { type: true },
    });

    const total = grouped.reduce((sum, g) => sum + g._count.type, 0);
    const byType = Object.fromEntries(
      grouped.map((g) => [g.type, g._count.type]),
    ) as Record<DocumentType, number>;

    return { total, byType };
  }

  /**
   * Upload a user-provided file (base64 → Buffer already decoded by controller),
   * store it in Supabase Storage, and create a Document record.
   * Used for compliance documents: driver licences, insurance certs, custom CMRs, etc.
   */
  async uploadDocument(
    userId: string,
    fileBuffer: Buffer,
    params: {
      mimeType: string;
      fileName: string;
      type: string;
      title: string;
      orderId?: string;
      transportJobId?: string;
      expiresAt?: string;
      notes?: string;
    },
  ) {
    const ext = params.fileName.split('.').pop() ?? 'bin';
    const storagePath = `uploads/${userId}/${Date.now()}_${Math.random().toString(36).slice(2, 8)}.${ext}`;
    await this.supabase.uploadFile('documents', storagePath, fileBuffer);
    const fileUrl = this.supabase.getPublicUrl('documents', storagePath);

    const links: Array<{
      entityType: DocumentEntityType;
      entityId: string;
      role: DocumentLinkRole;
    }> = [];
    if (params.orderId)
      links.push({
        entityType: DocumentEntityType.ORDER,
        entityId: params.orderId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (params.transportJobId)
      links.push({
        entityType: DocumentEntityType.TRANSPORT_JOB,
        entityId: params.transportJobId,
        role: DocumentLinkRole.PRIMARY,
      });

    return this.prisma.document.create({
      data: {
        title: params.title,
        type: params.type as DocumentType,
        status: DocumentStatus.ISSUED,
        fileUrl,
        mimeType: params.mimeType,
        fileSize: fileBuffer.length,
        ownerId: userId,
        orderId: params.orderId,
        transportJobId: params.transportJobId,
        expiresAt: params.expiresAt ? new Date(params.expiresAt) : undefined,
        notes: params.notes,
        isGenerated: false,
        links: links.length ? { create: links } : undefined,
      },
      include: { links: true },
    });
  }

  /**
   * Auto-generate invoice document records when an Invoice is created.
   * Called internally by OrdersService or InvoicesService.
   */
  async generateFromInvoice(
    invoiceId: string,
    invoiceNumber: string,
    ownerId: string,
    orderId: string,
    pdfUrl?: string,
  ) {
    return this.prisma.document.create({
      data: {
        title: `Invoice ${invoiceNumber}`,
        type: DocumentType.INVOICE,
        status: DocumentStatus.ISSUED,
        fileUrl: pdfUrl,
        mimeType: 'application/pdf',
        invoiceId,
        orderId,
        ownerId,
        isGenerated: true,
        links: {
          create: [
            {
              entityType: DocumentEntityType.INVOICE,
              entityId: invoiceId,
              role: DocumentLinkRole.PRIMARY,
            },
            {
              entityType: DocumentEntityType.ORDER,
              entityId: orderId,
              role: DocumentLinkRole.RELATED,
            },
          ],
        },
      },
    });
  }

  /**
   * Auto-generate weighing slip document when material weight is confirmed.
   */
  async generateWeighingSlip(
    orderId: string | undefined,
    ownerId: string,
    weight: number,
    unit: string,
    pdfUrl?: string,
    orderNumber?: string,
    transportJobId?: string,
    driverName?: string,
    pickupPhotoUrl?: string,
  ) {
    const entityId = orderId ?? transportJobId ?? 'unknown';
    let resolvedPdfUrl = pdfUrl;
    if (!resolvedPdfUrl) {
      try {
        const pdfBuffer = await this.buildWeighingSlipPdf({
          weight,
          unit,
          orderId: entityId,
          orderNumber,
          driverName,
          hasPickupPhoto: !!pickupPhotoUrl,
        });
        const storagePath = `weighing-slips/${entityId}_${Date.now()}.pdf`;
        await this.supabase.uploadFile('documents', storagePath, pdfBuffer);
        resolvedPdfUrl = this.supabase.getPublicUrl('documents', storagePath);
      } catch (err) {
        this.logger.warn(
          `Weighing slip PDF failed for ${orderId ? `order ${orderId}` : `job ${transportJobId}`}: ${(err as Error).message}`,
        );
      }
    }

    const linkEntity = orderId
      ? { entityType: DocumentEntityType.ORDER, entityId: orderId, role: DocumentLinkRole.PRIMARY }
      : {
          entityType: DocumentEntityType.TRANSPORT_JOB,
          entityId: transportJobId ?? entityId,
          role: DocumentLinkRole.PRIMARY,
        };

    return this.prisma.document.create({
      data: {
        title: `Svēršanas lapa — ${weight} ${unit}${orderNumber ? ` · #${orderNumber}` : ''}`,
        type: DocumentType.WEIGHING_SLIP,
        status: DocumentStatus.ISSUED,
        fileUrl: resolvedPdfUrl,
        mimeType: 'application/pdf',
        orderId: orderId ?? null,
        transportJobId: transportJobId ?? null,
        ownerId,
        isGenerated: true,
        notes: [
          `Svars: ${weight} ${unit}`,
          orderNumber ? `Pasūtījums #${orderNumber}` : null,
          driverName ? `Šoferis: ${driverName}` : null,
          pickupPhotoUrl ? `Svēršanas foto: ${pickupPhotoUrl}` : null,
        ]
          .filter(Boolean)
          .join(' · '),
        links: {
          create: linkEntity,
        },
      },
    });
  }

  /** Build a weighing slip PDF buffer. */
  private buildWeighingSlipPdf(params: {
    weight: number;
    unit: string;
    orderId: string;
    orderNumber?: string;
    driverName?: string;
    hasPickupPhoto?: boolean;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const slipNumber = `WS${Date.now().toString(36).toUpperCase()}`;
      const dateStr = new Date().toLocaleDateString('lv-LV');

      // ── Header ────────────────────────────────────────────────────────────
      doc
        .fontSize(22)
        .font('Helvetica-Bold')
        .text('B3Hub', 50, 50)
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text('b3hub.lv  |  support@b3hub.lv', 50, 76);

      doc
        .fontSize(19)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text('SVĒRŠANAS LAPA', 0, 50, { align: 'right' });

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text(`#${slipNumber}`, 0, 74, { align: 'right' });

      doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e5e7eb').stroke();

      // ── Details ───────────────────────────────────────────────────────────
      doc.fillColor('#111827').fontSize(10).font('Helvetica');
      const y = 116;
      const label = (text: string, row: number) =>
        doc.text(text, 50, y + row * 22);
      const value = (text: string, row: number) =>
        doc.text(text, 220, y + row * 22);

      label('Datums:', 0);
      value(dateStr, 0);

      if (params.orderNumber) {
        label('Pasūtījuma Nr.:', 1);
        value(`#${params.orderNumber}`, 1);
      }

      let nextRow = params.orderNumber ? 2 : 1;
      label('Svars:', nextRow);
      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(`${params.weight} ${params.unit}`, 220, y + nextRow * 22);
      nextRow++;

      if (params.driverName) {
        doc.fontSize(10).font('Helvetica').fillColor('#111827');
        label('Šoferis:', nextRow);
        value(params.driverName, nextRow);
        nextRow++;
      }

      if (params.hasPickupPhoto) {
        doc.fontSize(10).font('Helvetica').fillColor('#111827');
        label('Svēršanas foto:', nextRow);
        doc.fontSize(10).font('Helvetica').fillColor('#16a34a')
          .text('✓ Pieejams platformā', 220, y + nextRow * 22);
        doc.fillColor('#111827');
        nextRow++;
      }

      doc
        .moveTo(50, y + (nextRow + 1) * 22)
        .lineTo(545, y + (nextRow + 1) * 22)
        .strokeColor('#e5e7eb')
        .stroke();

      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .fillColor('#16a34a')
        .text('APSTIPRINĀTS ✓', 50, y + (nextRow + 1) * 22 + 12)
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text(
          `Apstiprināts B3Hub platformā · ${dateStr}`,
          50,
          y + (nextRow + 1) * 22 + 30,
        );

      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#9ca3af')
        .text(
          'B3Hub SIA  |  Rīga, Latvija  |  support@b3hub.lv  |  b3hub.lv',
          50,
          750,
          {
            align: 'center',
          },
        );

      doc.end();
    });
  }

  /**
   * Auto-generate a waste processing certificate when a waste record is created.
   * Called by RecyclingCentersService after a successful waste record creation.
   */
  async generateWasteCertificate(params: {
    ownerId: string;
    wasteRecordId: string;
    centerId?: string;
    centerName?: string;
    centerCity?: string;
    wasteType?: string;
    weightKg?: number;
    recyclableWeightKg?: number;
    recyclingRate?: number;
    processedDate?: Date;
  }) {
    const dateStr = (params.processedDate ?? new Date()).toLocaleDateString(
      'lv-LV',
    );
    const certNumber = `WC${Date.now().toString(36).toUpperCase()}`;

    let fileUrl: string | undefined;
    try {
      const pdfBuffer = await this.buildWasteCertPdf({
        ...params,
        certNumber,
        dateStr,
      });
      const storagePath = `waste-certs/${params.wasteRecordId}.pdf`;
      await this.supabase.uploadFile('documents', storagePath, pdfBuffer);
      fileUrl = this.supabase.getPublicUrl('documents', storagePath);
    } catch (err) {
      this.logger.warn(
        `Waste certificate PDF failed for record ${params.wasteRecordId}: ${(err as Error).message}`,
      );
    }

    return this.prisma.document.create({
      data: {
        title: `Atkritumu sertifikāts ${certNumber} — ${dateStr}`,
        type: DocumentType.WASTE_CERTIFICATE,
        status: DocumentStatus.ISSUED,
        fileUrl,
        mimeType: 'application/pdf',
        ownerId: params.ownerId,
        isGenerated: true,
        issuedBy: params.centerName,
        notes: params.wasteType
          ? `Atkritumu veids: ${params.wasteType}${params.weightKg ? ` · Svars: ${(params.weightKg / 1000).toFixed(3)} t` : ''}`
          : undefined,
        links: {
          create: {
            entityType: DocumentEntityType.WASTE_RECORD,
            entityId: params.wasteRecordId,
            role: DocumentLinkRole.PRIMARY,
          },
        },
      },
    });
  }

  /** Build a waste processing certificate PDF buffer. */
  private buildWasteCertPdf(params: {
    certNumber: string;
    dateStr: string;
    centerName?: string;
    centerCity?: string;
    wasteType?: string;
    weightKg?: number;
    recyclableWeightKg?: number;
    recyclingRate?: number;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ── Header ────────────────────────────────────────────────────────────
      doc
        .fontSize(22)
        .font('Helvetica-Bold')
        .text('B3Hub', 50, 50)
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text('b3hub.lv  |  support@b3hub.lv', 50, 76);

      doc
        .fontSize(19)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text('ATKRITUMU SERTIFIKĀTS', 0, 50, { align: 'right' });

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text(`#${params.certNumber}`, 0, 74, { align: 'right' });

      doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e5e7eb').stroke();

      // ── Details ───────────────────────────────────────────────────────────
      doc.fillColor('#111827').fontSize(10).font('Helvetica');
      const y = 116;
      const label = (text: string, row: number) =>
        doc.text(text, 50, y + row * 20);
      const value = (text: string, row: number) =>
        doc.text(text, 220, y + row * 20);

      label('Datums:', 0);
      value(params.dateStr, 0);

      if (params.centerName) {
        label('Pārstrādes centrs:', 1);
        value(
          `${params.centerName}${params.centerCity ? `, ${params.centerCity}` : ''}`,
          1,
        );
      }

      if (params.wasteType) {
        label('Atkritumu veids:', 2);
        value(params.wasteType, 2);
      }

      if (params.weightKg !== undefined) {
        label('Kopējais svars:', 3);
        value(`${(params.weightKg / 1000).toFixed(3)} t`, 3);
      }

      if (params.recyclableWeightKg !== undefined) {
        label('Pārstrādātais svars:', 4);
        value(`${(params.recyclableWeightKg / 1000).toFixed(3)} t`, 4);
      }

      if (params.recyclingRate !== undefined) {
        label('Pārstrādes koeficients:', 5);
        value(`${params.recyclingRate.toFixed(1)} %`, 5);
      }

      const stampY = y + 7 * 20;
      doc
        .moveTo(50, stampY)
        .lineTo(545, stampY)
        .strokeColor('#e5e7eb')
        .stroke();
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#16a34a')
        .text('PĀRSTRĀDĀTS ✓', 50, stampY + 12)
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text(
          `Apstiprināts B3Hub platformā · ${params.dateStr}`,
          50,
          stampY + 32,
        );

      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#9ca3af')
        .text(
          'B3Hub SIA  |  Rīga, Latvija  |  support@b3hub.lv  |  b3hub.lv',
          50,
          750,
          { align: 'center' },
        );

      doc.end();
    });
  }

  /**
   * Generates a PDF, uploads it to Supabase Storage, and creates a Document record.
   * Called internally by TransportJobsService on job ACCEPTED (DRAFT) and DELIVERED (SIGNED).
   *
   * For domestic orders (isInternational = false, default): produces a "Kravas pavadziime"
   * (Latvian cargo bill of lading). For cross-border orders: produces a "CMR Note".
   */
  async generateDeliveryNote(params: {
    orderId?: string;
    transportJobId?: string;
    ownerId: string;
    /** Additional owner (e.g. the driver) who should also receive a copy. */
    driverOwnerId?: string;
    /** Seller/supplier owner who should also receive a copy. */
    sellerOwnerId?: string;
    /** Initial document status — defaults to ISSUED. Pass DRAFT when pre-generating at job accept. */
    initialStatus?: DocumentStatus;
    /** true = cross-border shipment (CMR Convention); false = domestic (Kravas pavadziime) */
    isInternational?: boolean;
    jobNumber: string;
    pickupAddress?: string;
    pickupCity: string;
    deliveryAddress?: string;
    deliveryCity: string;
    driverName?: string;
    driverPhone?: string;
    vehiclePlate?: string;
    cargoType?: string;
    cargoWeightKg?: number;
    actualWeightKg?: number;
    orderNumber?: string;
    siteContactName?: string;
    deliveredAt?: Date;
    /** GPS coordinates captured at proof submission time. */
    proofLat?: number;
    proofLng?: number;
  }) {
    let fileUrl: string | undefined;

    try {
      const pdfBuffer = await this.buildCmrPdf(params);
      const storagePath = `cmr/${params.transportJobId ?? params.jobNumber}.pdf`;
      await this.supabase.uploadFile('documents', storagePath, pdfBuffer);
      fileUrl = this.supabase.getPublicUrl('documents', storagePath);
    } catch (err) {
      this.logger.warn(
        `CMR PDF generation/upload failed for job ${params.jobNumber}: ${(err as Error).message}`,
      );
      // Fall through — still create the document record without a file URL
    }

    const docTitle = params.isInternational
      ? `CMR Note — ${params.jobNumber}`
      : `Kravas pavadzīme — ${params.jobNumber}`;

    const noteData = {
      title: docTitle,
      type: DocumentType.DELIVERY_NOTE,
      status: params.initialStatus ?? DocumentStatus.ISSUED,
      fileUrl,
      mimeType: 'application/pdf',
      orderId: params.orderId,
      transportJobId: params.transportJobId,
      isGenerated: true,
      notes: `${params.pickupCity} → ${params.deliveryCity}${
        params.driverName ? ` · Šoferis: ${params.driverName}` : ''
      }`,
    };

    const linkEntries = [
      ...(params.orderId
        ? [
            {
              entityType: DocumentEntityType.ORDER,
              entityId: params.orderId,
              role: DocumentLinkRole.RELATED,
            },
          ]
        : []),
      ...(params.transportJobId
        ? [
            {
              entityType: DocumentEntityType.TRANSPORT_JOB,
              entityId: params.transportJobId,
              role: DocumentLinkRole.PRIMARY,
            },
          ]
        : []),
    ];

    // Create the buyer's document record
    const buyerDoc = await this.prisma.document.create({
      data: {
        ...noteData,
        ownerId: params.ownerId,
        links: linkEntries.length ? { create: linkEntries } : undefined,
      },
    });

    // Create a copy for the driver so they can also view/download the CMR
    if (params.driverOwnerId && params.driverOwnerId !== params.ownerId) {
      this.prisma.document
        .create({
          data: {
            ...noteData,
            ownerId: params.driverOwnerId,
            links: linkEntries.length ? { create: linkEntries } : undefined,
          },
        })
        .catch((err) =>
          this.logger.warn(
            `Driver CMR copy failed for job ${params.jobNumber}: ${(err as Error).message}`,
          ),
        );
    }

    // Create a copy for the seller/supplier
    if (
      params.sellerOwnerId &&
      params.sellerOwnerId !== params.ownerId &&
      params.sellerOwnerId !== params.driverOwnerId
    ) {
      this.prisma.document
        .create({
          data: {
            ...noteData,
            ownerId: params.sellerOwnerId,
            links: linkEntries.length ? { create: linkEntries } : undefined,
          },
        })
        .catch((err) =>
          this.logger.warn(
            `Seller CMR copy failed for job ${params.jobNumber}: ${(err as Error).message}`,
          ),
        );
    }

    return buyerDoc;
  }

  /** Build a CMR / delivery note PDF buffer. */
  private buildCmrPdf(params: {
    jobNumber: string;
    pickupAddress?: string;
    pickupCity: string;
    deliveryAddress?: string;
    deliveryCity: string;
    driverName?: string;
    driverPhone?: string;
    vehiclePlate?: string;
    cargoType?: string;
    cargoWeightKg?: number;
    actualWeightKg?: number;
    orderNumber?: string;
    siteContactName?: string;
    deliveredAt?: Date;
    isInternational?: boolean;
    proofLat?: number;
    proofLng?: number;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const dateStr = (params.deliveredAt ?? new Date()).toLocaleDateString(
        'lv-LV',
      );
      const weightDisplay = params.actualWeightKg
        ? `${(params.actualWeightKg / 1000).toFixed(3)} t (faktiskais)`
        : params.cargoWeightKg
          ? `${(params.cargoWeightKg / 1000).toFixed(3)} t`
          : '—';

      // ── Header ──────────────────────────────────────────────────────────
      doc
        .fontSize(22)
        .font('Helvetica-Bold')
        .text('B3Hub', 50, 50)
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text('b3hub.lv  |  support@b3hub.lv', 50, 76);

      doc
        .fontSize(22)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text(params.isInternational ? 'CMR NOTE' : 'KRAVAS PAVADZĪME', 0, 50, { align: 'right' });

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text(`#${params.jobNumber}`, 0, 76, { align: 'right' });

      // ── Divider ─────────────────────────────────────────────────────────
      doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e5e7eb').stroke();

      // ── Meta row ────────────────────────────────────────────────────────
      doc.fillColor('#111827').fontSize(10).font('Helvetica');
      const metaY = 114;
      doc.text('Datums:', 50, metaY).text(dateStr, 180, metaY);
      if (params.orderNumber) {
        doc
          .text('Pasūtījums:', 50, metaY + 18)
          .text(`#${params.orderNumber}`, 180, metaY + 18);
      }

      // ── Route section ───────────────────────────────────────────────────
      const routeY = params.orderNumber ? 172 : 154;
      doc
        .moveTo(50, routeY)
        .lineTo(545, routeY)
        .strokeColor('#e5e7eb')
        .stroke();
      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .fillColor('#374151')
        .text('MARŠRUTS', 50, routeY + 10)
        .font('Helvetica')
        .fillColor('#111827');

      const fromAddr = [params.pickupAddress, params.pickupCity]
        .filter(Boolean)
        .join(', ');
      const toAddr = [params.deliveryAddress, params.deliveryCity]
        .filter(Boolean)
        .join(', ');

      doc
        .fontSize(10)
        .text('No (iekraušana):', 50, routeY + 28)
        .text(fromAddr || params.pickupCity, 180, routeY + 28);
      doc
        .text('Uz (izkraušana):', 50, routeY + 46)
        .text(toAddr || params.deliveryCity, 180, routeY + 46);

      if (params.siteContactName) {
        doc
          .text('Saņēmējs:', 50, routeY + 64)
          .text(params.siteContactName, 180, routeY + 64);
      }

      // ── Cargo section ───────────────────────────────────────────────────
      const cargoY = routeY + (params.siteContactName ? 100 : 82);
      doc
        .moveTo(50, cargoY)
        .lineTo(545, cargoY)
        .strokeColor('#e5e7eb')
        .stroke();
      doc
        .font('Helvetica-Bold')
        .text('KRAVA', 50, cargoY + 10)
        .font('Helvetica')
        .fillColor('#111827');

      if (params.cargoType) {
        doc
          .text('Kravas veids:', 50, cargoY + 28)
          .text(params.cargoType, 180, cargoY + 28);
      }
      doc.text('Svars:', 50, cargoY + 46).text(weightDisplay, 180, cargoY + 46);

      // ── Transport section ────────────────────────────────────────────────
      const transY = cargoY + 86;
      doc
        .moveTo(50, transY)
        .lineTo(545, transY)
        .strokeColor('#e5e7eb')
        .stroke();
      doc
        .font('Helvetica-Bold')
        .text('PĀRVADĀTĀJS', 50, transY + 10)
        .font('Helvetica')
        .fillColor('#111827');

      if (params.driverName) {
        doc
          .text('Šoferis:', 50, transY + 28)
          .text(params.driverName, 180, transY + 28);
      }
      if (params.driverPhone) {
        doc
          .text('Telefons:', 50, transY + 46)
          .text(params.driverPhone, 180, transY + 46);
      }
      if (params.vehiclePlate) {
        doc
          .text('Transportlīdzeklis:', 50, transY + 64)
          .text(params.vehiclePlate, 180, transY + 64);
      }

      // ── Status stamp ────────────────────────────────────────────────────
      const stampY = transY + 110;
      doc
        .moveTo(50, stampY)
        .lineTo(545, stampY)
        .strokeColor('#e5e7eb')
        .stroke();
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#16a34a')
        .text('PIEGĀDĀTS ✓', 50, stampY + 12)
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text(`Apstiprināts B3Hub platformā · ${dateStr}`, 50, stampY + 32);

      if (params.proofLat != null && params.proofLng != null) {
        doc
          .fontSize(8)
          .font('Helvetica')
          .fillColor('#9ca3af')
          .text(
            `GPS: ${params.proofLat.toFixed(6)}, ${params.proofLng.toFixed(6)}`,
            50,
            stampY + 50,
          );
      }

      // ── Footer ───────────────────────────────────────────────────────────
      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#9ca3af')
        .text(
          'B3Hub SIA  |  Rīga, Latvija  |  support@b3hub.lv  |  b3hub.lv',
          50,
          750,
          { align: 'center' },
        );

      doc.end();
    });
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Waste transport note (Atkritumu pārvadājuma pavadzīme)
  // Required by Latvian Atkritumu apsaimniekošanas likums + Cabinet Reg. No. 712
  // before any waste disposal transport can legally take place.
  // Generated at order CONFIRMED for DISPOSAL orders.
  // ────────────────────────────────────────────────────────────────────────────

  /**
   * Pre-generate an atkritumu pārvadājuma pavadzīme for a waste disposal order.
   * Must exist before the transporter departs from the waste producer's site.
   * Creates copies for buyer (waste producer) and driver.
   */
  async generateWasteTransportNote(params: {
    orderId: string;
    ownerId: string; // waste producer (buyer) userId
    driverOwnerId?: string;
    orderNumber?: string;
    producerName?: string;    // waste producer company name
    producerAddress?: string;
    transporterName?: string; // carrier company name
    transporterRegNo?: string;
    receiverName?: string;    // recycling / waste management facility name
    receiverAddress?: string;
    receiverPermitNo?: string; // Atkritumu apsaimniekošanas atļaujas Nr.
    ewcCode?: string;          // European Waste Catalogue code (e.g. 17 05 04)
    wasteDescription?: string;
    estimatedWeightKg?: number;
    pickupDate?: Date;
  }) {
    const noteNumber = `ATP-${Date.now().toString(36).toUpperCase()}`;
    const dateStr = (params.pickupDate ?? new Date()).toLocaleDateString('lv-LV');

    let fileUrl: string | undefined;
    try {
      const pdfBuffer = await this.buildWasteTransportPdf({ ...params, noteNumber, dateStr });
      const storagePath = `waste-transport/${params.orderId}.pdf`;
      await this.supabase.uploadFile('documents', storagePath, pdfBuffer);
      fileUrl = this.supabase.getPublicUrl('documents', storagePath);
    } catch (err) {
      this.logger.warn(
        `Waste transport note PDF failed for order ${params.orderId}: ${(err as Error).message}`,
      );
    }

    const noteData = {
      title: `Atkritumu pārvadājuma pavadzīme ${noteNumber}`,
      type: DocumentType.WASTE_TRANSPORT_NOTE,
      status: DocumentStatus.ISSUED,
      fileUrl,
      mimeType: 'application/pdf',
      orderId: params.orderId,
      isGenerated: true,
      issuedBy: 'B3Hub',
      notes: params.ewcCode
        ? `EWC: ${params.ewcCode}${params.wasteDescription ? ` — ${params.wasteDescription}` : ''}`
        : params.wasteDescription,
      links: {
        create: {
          entityType: DocumentEntityType.ORDER,
          entityId: params.orderId,
          role: DocumentLinkRole.PRIMARY,
        },
      },
    };

    // Buyer copy
    const buyerDoc = await this.prisma.document.create({
      data: { ...noteData, ownerId: params.ownerId },
    });

    // Driver copy (fire-and-forget)
    if (params.driverOwnerId && params.driverOwnerId !== params.ownerId) {
      this.prisma.document
        .create({ data: { ...noteData, ownerId: params.driverOwnerId } })
        .catch((err) =>
          this.logger.warn(
            `Driver waste transport note copy failed for order ${params.orderId}: ${(err as Error).message}`,
          ),
        );
    }

    return buyerDoc;
  }

  /**
   * Update an existing DRAFT delivery note to SIGNED after driver delivers.
   * Returns null if no draft found (caller should then create a new SIGNED note).
   */
  async signDeliveryNote(transportJobId: string): Promise<boolean> {
    const existing = await this.prisma.document.findFirst({
      where: {
        transportJobId,
        type: DocumentType.DELIVERY_NOTE,
        status: DocumentStatus.DRAFT,
      },
      select: { id: true },
    });
    if (!existing) return false;

    await this.prisma.document.updateMany({
      where: {
        transportJobId,
        type: DocumentType.DELIVERY_NOTE,
        status: DocumentStatus.DRAFT,
      },
      data: { status: DocumentStatus.SIGNED },
    });
    return true;
  }

  /** Build an atkritumu pārvadājuma pavadzīme PDF. */
  private buildWasteTransportPdf(params: {
    noteNumber: string;
    dateStr: string;
    orderNumber?: string;
    producerName?: string;
    producerAddress?: string;
    transporterName?: string;
    transporterRegNo?: string;
    receiverName?: string;
    receiverAddress?: string;
    receiverPermitNo?: string;
    ewcCode?: string;
    wasteDescription?: string;
    estimatedWeightKg?: number;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ── Header ─────────────────────────────────────────────────────────────
      doc
        .fontSize(22)
        .font('Helvetica-Bold')
        .text('B3Hub', 50, 50)
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text('b3hub.lv  |  support@b3hub.lv', 50, 76);

      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text('ATKRITUMU PĀRVADĀJUMA PAVADZĪME', 0, 50, { align: 'right' });

      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#6b7280')
        .text(`#${params.noteNumber}`, 0, 72, { align: 'right' });

      doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e5e7eb').stroke();

      // ── Details ────────────────────────────────────────────────────────────
      doc.fillColor('#111827').fontSize(10).font('Helvetica');
      const y = 116;
      let row = 0;
      const label = (text: string) =>
        doc.text(text, 50, y + row * 20).font('Helvetica');
      const value = (text: string) => {
        doc.font('Helvetica').text(text, 220, y + row * 20);
        row++;
      };

      label('Datums:'); value(params.dateStr);
      if (params.orderNumber) { label('Pasūtījuma Nr.:'); value(`#${params.orderNumber}`); }

      // EWC / waste type
      doc.moveTo(50, y + row * 20 + 4).lineTo(545, y + row * 20 + 4).strokeColor('#e5e7eb').stroke();
      row++;
      doc.font('Helvetica-Bold').text('ATKRITUMI', 50, y + row * 20).font('Helvetica');
      row++;
      if (params.ewcCode) { label('EWC kods:'); value(params.ewcCode); }
      if (params.wasteDescription) { label('Atkritumu veids:'); value(params.wasteDescription); }
      if (params.estimatedWeightKg !== undefined) {
        label('Paredzamais svars:');
        value(`${(params.estimatedWeightKg / 1000).toFixed(3)} t`);
      }

      // Producer
      doc.moveTo(50, y + row * 20 + 4).lineTo(545, y + row * 20 + 4).strokeColor('#e5e7eb').stroke();
      row++;
      doc.font('Helvetica-Bold').text('ATKRITUMU RAŽOTĀJS', 50, y + row * 20).font('Helvetica');
      row++;
      if (params.producerName) { label('Nosaukums:'); value(params.producerName); }
      if (params.producerAddress) { label('Adrese:'); value(params.producerAddress); }

      // Transporter
      doc.moveTo(50, y + row * 20 + 4).lineTo(545, y + row * 20 + 4).strokeColor('#e5e7eb').stroke();
      row++;
      doc.font('Helvetica-Bold').text('PĀRVADĀTĀJS', 50, y + row * 20).font('Helvetica');
      row++;
      if (params.transporterName) { label('Nosaukums:'); value(params.transporterName); }
      if (params.transporterRegNo) { label('Reģ. Nr.:'); value(params.transporterRegNo); }

      // Receiver
      doc.moveTo(50, y + row * 20 + 4).lineTo(545, y + row * 20 + 4).strokeColor('#e5e7eb').stroke();
      row++;
      doc.font('Helvetica-Bold').text('SAŅĒMĒJS', 50, y + row * 20).font('Helvetica');
      row++;
      if (params.receiverName) { label('Nosaukums:'); value(params.receiverName); }
      if (params.receiverAddress) { label('Adrese:'); value(params.receiverAddress); }
      if (params.receiverPermitNo) { label('Atļaujas Nr.:'); value(params.receiverPermitNo); }

      // Footer
      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#9ca3af')
        .text(
          'B3Hub SIA  |  Rīga, Latvija  |  support@b3hub.lv  |  b3hub.lv',
          50,
          750,
          { align: 'center' },
        );

      doc.end();
    });
  }
}
