/**
 * Documents service.
 * Compliance documents (licenses, certificates, waste consignment notes).
 * Handles Supabase Storage uploads, status tracking (pending/approved/rejected),
 * signed download URLs, and expiry-date monitoring.
 */
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import {
  DocumentEntityType,
  DocumentLinkRole,
  DocumentType,
  DocumentStatus,
  Prisma,
} from '@prisma/client';
import { QueryDocumentsDto } from './dto/query-documents.dto';
import { CreateDocumentDto } from './dto/create-document.dto';

@Injectable()
export class DocumentsService {
  private readonly logger = new Logger(DocumentsService.name);

  constructor(private readonly prisma: PrismaService) {}

  /** List all documents visible to the requesting user */
  async findAll(userId: string, query: QueryDocumentsDto) {
    const where: Prisma.DocumentWhereInput = {
      ownerId: userId,
    };

    if (query.type) where.type = query.type;
    if (query.status) where.status = query.status;
    if (query.orderId) where.orderId = query.orderId;
    if (query.entityType && query.entityId) {
      where.links = {
        some: {
          entityType: query.entityType,
          entityId: query.entityId,
        },
      };
    }

    if (query.search) {
      where.OR = [
        { title: { contains: query.search, mode: 'insensitive' } },
        { issuedBy: { contains: query.search, mode: 'insensitive' } },
        { notes: { contains: query.search, mode: 'insensitive' } },
      ];
    }

    const [documents, total] = await Promise.all([
      this.prisma.document.findMany({
        where,
        include: { links: true },
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.document.count({ where }),
    ]);

    return { documents, total };
  }

  /** Get a single document by id (only if owned by user) */
  async findOne(id: string, userId: string) {
    const doc = await this.prisma.document.findFirst({
      where: { id, ownerId: userId },
      include: { links: true },
    });
    if (!doc) throw new NotFoundException('Document not found');
    return doc;
  }

  /** Create a document (e.g. uploaded by user or generated by system) */
  async create(userId: string, dto: CreateDocumentDto) {
    const { links, ...documentData } = dto;

    const directLinks: Array<{
      entityType: DocumentEntityType;
      entityId: string;
      role: DocumentLinkRole;
    }> = [];

    if (dto.orderId)
      directLinks.push({
        entityType: DocumentEntityType.ORDER,
        entityId: dto.orderId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.invoiceId)
      directLinks.push({
        entityType: DocumentEntityType.INVOICE,
        entityId: dto.invoiceId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.transportJobId)
      directLinks.push({
        entityType: DocumentEntityType.TRANSPORT_JOB,
        entityId: dto.transportJobId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.wasteRecordId)
      directLinks.push({
        entityType: DocumentEntityType.WASTE_RECORD,
        entityId: dto.wasteRecordId,
        role: DocumentLinkRole.PRIMARY,
      });
    if (dto.skipHireId)
      directLinks.push({
        entityType: DocumentEntityType.SKIP_HIRE_ORDER,
        entityId: dto.skipHireId,
        role: DocumentLinkRole.PRIMARY,
      });

    return this.prisma.document.create({
      data: {
        ...documentData,
        ownerId: userId,
        status: dto.status ?? DocumentStatus.ISSUED,
        links:
          links?.length || directLinks.length
            ? {
                create: [
                  ...directLinks,
                  ...(links?.map((l) => ({
                    entityType: l.entityType,
                    entityId: l.entityId,
                    role: l.role ?? DocumentLinkRole.RELATED,
                  })) ?? []),
                ],
              }
            : undefined,
      },
      include: { links: true },
    });
  }

  /** List documents by entity context (order, invoice, framework contract, etc.). */
  async findByContext(
    userId: string,
    entityType: DocumentEntityType,
    entityId: string,
  ) {
    return this.prisma.document.findMany({
      where: {
        ownerId: userId,
        links: {
          some: { entityType, entityId },
        },
      },
      include: { links: true },
      orderBy: { createdAt: 'desc' },
    });
  }

  /** Attach an existing document to an additional business entity. */
  async addLink(
    userId: string,
    documentId: string,
    entityType: DocumentEntityType,
    entityId: string,
    role: DocumentLinkRole = DocumentLinkRole.RELATED,
  ) {
    const doc = await this.prisma.document.findFirst({
      where: { id: documentId, ownerId: userId },
      select: { id: true },
    });
    if (!doc) throw new NotFoundException('Document not found');

    await this.prisma.documentLink.upsert({
      where: {
        documentId_entityType_entityId_role: {
          documentId,
          entityType,
          entityId,
          role,
        },
      },
      update: {},
      create: {
        documentId,
        entityType,
        entityId,
        role,
      },
    });

    return this.findOne(documentId, userId);
  }

  /** Remove one context link from a document. */
  async removeLink(userId: string, documentId: string, linkId: string) {
    const doc = await this.prisma.document.findFirst({
      where: { id: documentId, ownerId: userId },
      select: { id: true },
    });
    if (!doc) throw new NotFoundException('Document not found');

    const link = await this.prisma.documentLink.findFirst({
      where: { id: linkId, documentId },
      select: { id: true },
    });
    if (!link) throw new NotFoundException('Document link not found');

    await this.prisma.documentLink.delete({ where: { id: linkId } });
    return { success: true };
  }

  /** Summary counts per type for the authenticated user */
  async summary(userId: string) {
    const grouped = await this.prisma.document.groupBy({
      by: ['type'],
      where: { ownerId: userId },
      _count: { type: true },
    });

    const total = grouped.reduce((sum, g) => sum + g._count.type, 0);
    const byType = Object.fromEntries(
      grouped.map((g) => [g.type, g._count.type]),
    ) as Record<DocumentType, number>;

    return { total, byType };
  }

  /**
   * Auto-generate invoice document records when an Invoice is created.
   * Called internally by OrdersService or InvoicesService.
   */
  async generateFromInvoice(
    invoiceId: string,
    invoiceNumber: string,
    ownerId: string,
    orderId: string,
    pdfUrl?: string,
  ) {
    return this.prisma.document.create({
      data: {
        title: `Invoice ${invoiceNumber}`,
        type: DocumentType.INVOICE,
        status: DocumentStatus.ISSUED,
        fileUrl: pdfUrl,
        mimeType: 'application/pdf',
        invoiceId,
        orderId,
        ownerId,
        isGenerated: true,
        links: {
          create: [
            {
              entityType: DocumentEntityType.INVOICE,
              entityId: invoiceId,
              role: DocumentLinkRole.PRIMARY,
            },
            {
              entityType: DocumentEntityType.ORDER,
              entityId: orderId,
              role: DocumentLinkRole.RELATED,
            },
          ],
        },
      },
    });
  }

  /**
   * Auto-generate weighing slip document when material weight is confirmed.
   */
  async generateWeighingSlip(
    orderId: string,
    ownerId: string,
    weight: number,
    unit: string,
    pdfUrl?: string,
  ) {
    return this.prisma.document.create({
      data: {
        title: `Weighing Slip — ${weight} ${unit}`,
        type: DocumentType.WEIGHING_SLIP,
        status: DocumentStatus.ISSUED,
        fileUrl: pdfUrl,
        mimeType: 'application/pdf',
        orderId,
        ownerId,
        isGenerated: true,
        notes: `Confirmed weight: ${weight} ${unit}`,
        links: {
          create: {
            entityType: DocumentEntityType.ORDER,
            entityId: orderId,
            role: DocumentLinkRole.PRIMARY,
          },
        },
      },
    });
  }

  /**
   * Auto-generate a delivery note (CMR) when a transport job is delivered.
   * Called internally by TransportJobsService.
   */
  async generateDeliveryNote(
    params: {
      orderId?: string;
      transportJobId?: string;
      ownerId: string;
      jobNumber: string;
      pickupCity: string;
      deliveryCity: string;
      driverName?: string;
    },
    pdfUrl?: string,
  ) {
    return this.prisma.document.create({
      data: {
        title: `Delivery Note — ${params.jobNumber}`,
        type: DocumentType.DELIVERY_NOTE,
        status: DocumentStatus.ISSUED,
        fileUrl: pdfUrl,
        mimeType: 'application/pdf',
        orderId: params.orderId,
        transportJobId: params.transportJobId,
        ownerId: params.ownerId,
        isGenerated: true,
        notes: `${params.pickupCity} → ${params.deliveryCity}${
          params.driverName ? ` · Driver: ${params.driverName}` : ''
        }`,
        links: {
          create: [
            ...(params.orderId
              ? [
                  {
                    entityType: DocumentEntityType.ORDER,
                    entityId: params.orderId,
                    role: DocumentLinkRole.RELATED,
                  },
                ]
              : []),
            ...(params.transportJobId
              ? [
                  {
                    entityType: DocumentEntityType.TRANSPORT_JOB,
                    entityId: params.transportJobId,
                    role: DocumentLinkRole.PRIMARY,
                  },
                ]
              : []),
          ],
        },
      },
    });
  }
}
