import { StyleSheet, Platform } from 'react-native';
import { colors } from '@/lib/theme';

export const sa = StyleSheet.create({
  // ── Common
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  headerTitle: { fontSize: 17, fontWeight: '700', color: colors.textPrimary },
  headerSub: { fontSize: 12, color: colors.textDisabled, fontWeight: '500', marginTop: 2 },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaBtn: {
    backgroundColor: colors.primary,
    borderRadius: 100,
    paddingVertical: 16,
    alignItems: 'center',
  },
  ctaBtnGreen: { backgroundColor: '#059669' },
  ctaBtnDisabled: { backgroundColor: '#e5e7eb' },
  ctaBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Inter_700Bold',
    letterSpacing: 0.3,
  },
  ctaBtnTextDisabled: { color: colors.textDisabled },
  floatingCta: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 8,
  },
  // Floating CTA for map step (shown over transparent sheet)
  mapFloatingCta: {
    position: 'absolute',
    left: 20,
    right: 20,
  },

  // ── Map search card — absolute positioned at top, separate from sheet ──────
  mapSearchCard: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 30,
  },
  // ── Single unified floating card (search + GPS + suggestions) ──────────────
  mapCardShadow: {
    marginHorizontal: 16,
    marginTop: 6,
    borderRadius: 16,
    backgroundColor: '#fff',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.14,
        shadowRadius: 14,
      },
      android: { elevation: 6 },
    }),
  },
  mapCard: {
    borderRadius: 16,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  mapCardSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  mapCardDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.bgMuted,
  },
  mapSearchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    padding: 0,
  },
  mapMyLocIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  mapSuggRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 12,
  },
  mapSuggDotCol: {
    width: 20,
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  mapSuggDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  mapSuggLineTop: {
    width: 1,
    flex: 1,
    backgroundColor: '#e5e7eb',
    marginBottom: 2,
  },
  mapSuggLineBottom: {
    width: 1,
    flex: 1,
    backgroundColor: '#e5e7eb',
    marginTop: 2,
  },
  mapSuggText: { flex: 1, fontSize: 14, color: colors.textPrimary, lineHeight: 20 },
  mapConfirmedRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#f0fdf4',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginHorizontal: 16,
    marginTop: 4,
  },
  mapConfirmedText: { flex: 1, fontSize: 13, color: colors.success, lineHeight: 18 },

  // ── Map step
  mapTopBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: 6,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
    gap: 8,
  },
  placesInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgMuted,
    borderRadius: 12,
    height: 44,
    gap: 6,
  },
  placesTextInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '500',
    paddingRight: 12,
  },
  placesList: {
    marginTop: 4,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.bgCard,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    maxHeight: 200,
  },
  placesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f9fafb',
  },
  placesDesc: { fontSize: 13, color: colors.textSecondary, flex: 1 },

  mapHintStrip: {
    position: 'absolute',
    bottom: 180,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.92)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  mapHintText: { fontSize: 13, color: colors.textSecondary, fontWeight: '500' },

  // ── Floating back button (top-left, always over map) ────────
  mapBackBtn: {
    position: 'absolute',
    left: 16,
    zIndex: 50,
  },

  // ── Map FAB buttons (satellite toggle + locate-me) ──────────
  mapFabColumn: {
    position: 'absolute',
    right: 14,
    gap: 10,
    alignItems: 'center',
  },
  mapFab: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  mapFabActive: {
    backgroundColor: colors.primary,
  },

  // ── Reset pin button in bottom sheet ─────────────────────────
  resetBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },

  markerWrap: { alignItems: 'center' },
  markerOuter: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#111827',
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 4,
  },
  markerInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#fff' },
  markerStem: { width: 3, height: 10, backgroundColor: colors.primary, borderRadius: 2 },

  mapBottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -4 },
    elevation: 12,
    gap: 14,
  },
  addressRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  addressDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
    marginTop: 5,
    flexShrink: 0,
  },
  addressText: { flex: 1, fontSize: 15, color: colors.textPrimary, fontWeight: '500', lineHeight: 22 },
  mapEmptyHint: { textAlign: 'center', fontSize: 14, color: colors.textDisabled, paddingVertical: 10 },

  // ── Configure step
  configScroll: { paddingHorizontal: 20, paddingBottom: 24, paddingTop: 16, gap: 18 },

  materialCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  materialIcon: { fontSize: 28 },
  materialName: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  materialSup: { fontSize: 12, color: colors.textDisabled, marginTop: 2 },
  materialPrice: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },

  locationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  locationCardText: { flex: 1, fontSize: 13, color: colors.textSecondary, fontWeight: '500' },
  locationChange: { fontSize: 13, color: colors.textPrimary, fontWeight: '600' },

  section: { gap: 10 },
  sectionLabel: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },

  fractionChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  fractionChipActive: { backgroundColor: colors.primary, borderColor: colors.textPrimary },
  fractionChipText: { fontSize: 13, fontWeight: '600', color: colors.textSecondary },
  fractionChipTextActive: { color: '#fff' },

  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  stepperBtn: { width: 64, paddingVertical: 18, alignItems: 'center', backgroundColor: colors.bgSubtle },
  stepperBtnText: { fontSize: 24, fontWeight: '300', color: colors.textPrimary },
  stepperDisplay: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: 4,
  },
  stepperValue: { fontSize: 32, fontWeight: '800', color: colors.textPrimary },
  stepperUnit: { fontSize: 14, color: colors.textDisabled, fontWeight: '500' },

  qtyQuick: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.bgMuted,
  },
  qtyQuickActive: { backgroundColor: colors.primary },
  qtyQuickText: { fontSize: 12, color: colors.textMuted, fontWeight: '600' },
  qtyQuickTextActive: { color: '#fff' },

  vehicleCard: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  vehicleCardActive: { borderColor: colors.textPrimary, backgroundColor: colors.bgSubtle },
  vehicleEmoji: { fontSize: 24 },
  vehicleLabel: { fontSize: 13, fontWeight: '700', color: colors.textSecondary },
  vehicleLabelActive: { color: colors.textPrimary },
  vehicleSub: { fontSize: 10, color: colors.textDisabled },

  estimateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  estimateLabel: { fontSize: 14, color: colors.textSecondary, fontWeight: '500' },
  estimateValue: { fontSize: 22, fontWeight: '800', color: colors.textPrimary },

  // ── Searching step
  searchingScreen: {
    flex: 1,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
    gap: 14,
  },
  searchingTitle: { fontSize: 24, fontWeight: '800', color: '#fff', textAlign: 'center' },
  searchingDesc: { fontSize: 15, color: '#94a3b8', textAlign: 'center', lineHeight: 23 },
  searchingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#1e293b',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginTop: 8,
  },
  searchingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primaryMid,
  },
  searchingDotActive: {
    backgroundColor: '#4ade80',
  },
  searchingSummary: {
    width: '100%',
    backgroundColor: '#1e293b',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 6,
    marginTop: 4,
  },
  searchingSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 12,
  },
  searchingSummaryDivider: {
    height: 1,
    backgroundColor: '#334155',
  },
  searchingSummaryLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '500',
  },
  searchingSummaryValue: {
    fontSize: 13,
    color: '#e2e8f0',
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },
  searchingPillText: { fontSize: 13, color: '#94a3b8', fontWeight: '600' },

  ringContainer: {
    width: 150,
    height: 150,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  ring: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: colors.textSecondary,
  },
  ringCenter: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#1e293b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: '#dcfce7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  dimText: { color: '#64748b', fontSize: 14, marginTop: 4 },

  // ── Quotes step
  quoteCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    gap: 12,
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  quoteCardSelected: { borderColor: colors.textPrimary },
  recommendedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 4,
    marginBottom: -4,
  },
  recommendedText: { fontSize: 11, fontWeight: '700', color: '#fff' },
  quoteTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  supplierIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  supplierName: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
  supplierCity: { fontSize: 12, color: colors.textDisabled, marginTop: 2 },
  quotePrice: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
  quoteUnit: { fontSize: 13, fontWeight: '400', color: colors.textDisabled },
  quoteTotal: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  quoteMeta: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  quoteMetaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.bgMuted,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  selectedChip: { backgroundColor: '#dcfce7' },
  quoteMetaText: { fontSize: 11, color: colors.textMuted, fontWeight: '600' },

  // ── RFQ fallback CTA card
  rfqFallbackCard: {
    backgroundColor: '#f0f9ff',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#bae6fd',
    gap: 4,
  },
  rfqFallbackTitle: { fontSize: 15, fontWeight: '700', color: '#0369a1' },
  rfqFallbackDesc: { fontSize: 13, color: colors.textSecondary },

  // ── Confirm / Summary
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  summaryTitle: { fontSize: 15, fontWeight: '800', color: colors.textPrimary, marginBottom: 2 },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryLabel: { fontSize: 13, color: colors.textDisabled, fontWeight: '500' },
  summaryValue: { fontSize: 13, color: colors.textPrimary, fontWeight: '600' },
  summaryDivider: { height: 1, backgroundColor: colors.bgMuted },

  totalCard: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    padding: 22,
    alignItems: 'center',
    gap: 4,
  },
  totalLabel: { fontSize: 13, color: '#94a3b8', fontWeight: '500' },
  totalValue: { fontSize: 38, fontWeight: '900', color: '#fff', letterSpacing: -1.5 },
  totalNote: { fontSize: 11, color: '#64748b', marginTop: 4, textAlign: 'center' },

  // ── Flow Progress bar
  progressWrap: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressDotActive: { backgroundColor: colors.primary },
  progressDotInactive: { backgroundColor: colors.bgMuted },
  progressNum: { fontSize: 11, fontWeight: '700' },
  progressNumActive: { color: '#fff' },
  progressNumInactive: { color: colors.textDisabled },
  progressCheck: {},
  progressLine: { flex: 1, height: 2, marginHorizontal: 3 },
  progressLineActive: { backgroundColor: colors.primary },
  progressLineInactive: { backgroundColor: '#e5e7eb' },

  // ── Onboarding
  onboardingScreen: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  skipBtn: { position: 'absolute', top: 56, right: 28 },
  skipText: { fontSize: 14, color: colors.textDisabled, fontWeight: '600' },
  onboardingIllustration: { alignItems: 'center', justifyContent: 'center' },
  onboardingIconCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingIcon: { fontSize: 64 },
  onboardingWatermark: {
    position: 'absolute',
    fontSize: 96,
    fontWeight: '900',
    opacity: 0.07,
    zIndex: -1,
  },
  onboardDotsRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  onboardDot: { width: 8, height: 8, borderRadius: 4 },
  onboardDotActive: { width: 24, borderRadius: 4 },
  onboardDotInactive: { backgroundColor: '#e5e7eb' },
  onboardingContent: { alignItems: 'center', gap: 8, paddingHorizontal: 4 },
  onboardingStepLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  onboardingTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    lineHeight: 32,
  },
  onboardingDesc: { fontSize: 15, color: colors.textMuted, textAlign: 'center', lineHeight: 22 },

  // ── Material header address
  headerAddressRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  headerAddress: { fontSize: 11, color: colors.textDisabled, fontWeight: '500', maxWidth: 200 },

  // ── Material search bar
  matSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 8,
  },
  matSearchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '500',
    paddingVertical: 0,
  },
  matSearchClear: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#9ca3af',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Material card list
  matList: { paddingHorizontal: 16, paddingBottom: 100, gap: 8 },
  matCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  matCardBody: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    gap: 12,
  },
  matCardIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  matCardIcon: { fontSize: 22 },
  matCardName: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  matCardSup: { fontSize: 12, color: colors.textMuted, fontWeight: '400', lineHeight: 17 },
  matCardPrice: { fontSize: 15, fontWeight: '800', color: colors.textPrimary },
  matCardUnit: { fontSize: 11, fontWeight: '500', color: colors.textDisabled },
  recycledBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  recycledText: { fontSize: 9, color: colors.successText, fontWeight: '700' },
  selectBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: colors.primary,
  },
  selectBtnText: { fontSize: 11, color: '#fff', fontWeight: '700' },
  matEmpty: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 60,
    gap: 8,
  },
  matEmptyEmoji: { fontSize: 40 },
  matEmptyTitle: { fontSize: 16, fontWeight: '700', color: colors.textSecondary },
  matEmptyDesc: { fontSize: 14, color: colors.textDisabled, textAlign: 'center', paddingHorizontal: 20 },

  // ── Uber-style sheet ─────────────────────────────────────────
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    // top set dynamically via mapHeight; backgroundColor animated via sheetBg (transparent on map step)
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: -4 },
    elevation: 12,
  },
  sheetHandleWrap: { alignItems: 'center', paddingTop: 10, paddingBottom: 4 },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#e5e7eb' },
  sheetTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 12,
    gap: 8,
  },
  sheetTitle: { fontSize: 18, fontWeight: '700', color: colors.textPrimary },
  sheetSub: { fontSize: 13, color: colors.textDisabled, marginTop: 2 },
  sheetCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetSlideClip: { flex: 1, overflow: 'hidden' },
  sheetSlideWrapper: { flex: 1 },
  sheetFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: '#fff',
  },
  backFooterBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Contact / Notes inputs ────────────────────────────────────────────────
  contactInput: {
    backgroundColor: colors.bgSubtle,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: colors.textPrimary,
  },

  // ── Map step address card ──────────────────────────────────
  mapAddressCard: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.bgSubtle,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    margin: 20,
  },
});
